# ILD分割完整流程配置文件
# 支持数据预处理、训练、推理的统一配置

# ============================================================================
# 全局配置
# ============================================================================
global:
  # 项目名称
  project_name: "ILD_Segmentation"
  # 工作目录
  work_dir: "./workspace"
  # 随机种子
  seed: 42
  # GPU设备
  device: "cuda:0"
  # 日志级别
  log_level: "INFO"

# ============================================================================
# 数据路径配置
# ============================================================================
data:
  # 原始数据路径
  raw_data:
    ct_dir: "../dataset/images"
    label_dir: "../dataset/labels"
    lung_dir: "../dataset/lungs"
    annotations_file: "../dataset/annotations/processed/processed_labels.jsonl"
    lesion_analysis_file: "../dataset/patient_lesion_analysis.json"
  
  # 病变类型映射
  lesion_type_mapping:
    0: "background"
    1: "GGO"
    2: "reticulation"
    3: "consolidation"
    4: "honeycombing"
  
  # 预处理数据路径
  preprocessed:
    output_dir: "./data/preprocessed"
    npy_dir: "./data/npy"
    npz_dir: "./data/npz"
  
  # 文件命名模式
  naming:
    ct_suffix: "_0000.nii.gz"
    label_suffix: ".nii.gz"
    lung_patterns:
      - "{case_name}_lung_mask.nii.gz"

# ============================================================================
# 数据预处理配置
# ============================================================================
preprocessing:
  # 数据划分
  data_split:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
    stratified: true  # 基于疾病类型分层
  
  # 背景切片处理
  background_slices:
    enabled: true
    # 各数据集中背景切片的比例
    ratios:
      train: 0.3  # 训练集中30%为背景切片
      val: 0.2    # 验证集中20%为背景切片
      test: 0.2   # 测试集中20%为背景切片
    # 解剖位置分层采样
    anatomical_sampling:
      enabled: true
      # 按CT切片位置分层（上、中、下肺野）
      position_groups: 3
      # 每个位置组的最小切片数
      min_slices_per_group: 5
    # 背景切片选择策略
    selection_strategy:
      # 排除边缘切片（避免肺外区域）
      exclude_edge_ratio: 0.1  # 排除前后10%的切片
      # 优先选择肺组织丰富的切片
      prefer_lung_rich: true
      # 最小肺组织面积阈值
      min_lung_area: 1000  # 像素数
  

  
  # CT图像处理
  ct_processing:
    window_level: 40
    window_width: 400
    output_size: [256, 256]
    convert_to_3channel: true
    normalize_range: [0, 255]
  
  # 标签处理
  label_processing:
    # 连通组件清理
    clean_3d:
      enabled: true
      threshold: 1000  # 体素数
      connectivity: 26
    clean_2d:
      enabled: true
      threshold: 100   # 像素数
      connectivity: 8
    # 标签值验证
    validate_range: [0, 10]
  
  # 肺分割处理
  lung_processing:
    bbox_padding: 5
    fallback_to_hu: true
    hu_range: [-1000, 200]
  
  # 质量控制
  quality_control:
    min_slices_per_patient: 1
    min_lesion_area: 10
    check_file_integrity: true
  
  # 输出控制
  output:
    save_patient_splits: true
    save_slice_metadata: true
    save_statistics: true
    metadata_format: "json"

# ============================================================================
# 训练配置（预留）
# ============================================================================
training:
  # 模型配置
  model:
    name: "sam2"
    config_file: "sam2_hiera_t.yaml"
    checkpoint: "./checkpoints/sam2_hiera_tiny.pt"
  
  # 训练参数
  params:
    epochs: 10
    batch_size: 16
    learning_rate: 5e-5
    weight_decay: 1e-4
  
  # 学习率调度器
  scheduler:
    type: "cosine_annealing"  # 余弦退火
    warmup_ratio: 0.1         # warmup占总训练步数的比例
    min_lr_ratio: 0.01        # 最小学习率与初始学习率的比例
    warmup_type: "linear"     # warmup类型：linear
  
  # 数据加载
  dataloader:
    num_workers: 4
    pin_memory: true
    shuffle: true
    bbox_shift: 20  # 边界框随机扰动像素数
  
  # 损失函数
  loss:
    dice_weight: 1.0
    ce_weight: 1.0
    background_weight: 0.5  # 背景类别权重
    lesion_weight: 1.0      # 病变类别权重
  
  # 保存配置
  checkpoint:
    save_dir: "./checkpoints"
    save_interval: 50
    keep_best: true

# ============================================================================
# 推理配置
# ============================================================================
inference:
  # 模型配置
  model:
    # 训练好的MedSAM2模型路径
    model_path: "./workspace/best_model.pth"
    # SAM2配置文件
    config_path: "sam2_hiera_t.yaml"
    # SAM2预训练模型路径
    sam2_checkpoint: "./checkpoints/sam2_hiera_tiny.pt"
  
  # 数据配置
  data:
    # 输入数据根目录
    data_root: "./data/test"
    # 肺分割文件目录（可选）
    lung_mask_dir: "./data/lungs"
    # 输出结果目录
    output_dir: "./results/inference"
  
  # 推理参数
  params:
    # 计算设备
    device: "cuda:0"
    # 置信度阈值（低于此值认为是背景切片）
    confidence_threshold: 0.3
    # 边界框padding像素数
    bbox_padding: 5
    # 批处理大小
    batch_size: 1
    # 最小病变区域大小（像素）
    min_lesion_size: 10
    # 最大连通组件数量
    max_components: 5
  
  # 输出配置
  output:
    # 是否保存可视化结果
    save_visualization: true
    # 是否保存NIfTI格式结果
    save_nifti: false
    # 是否详细输出
    verbose: true
    # 结果文件格式
    formats:
      - "npz"  # numpy压缩格式
      - "json" # JSON摘要格式
  
  # 病变类型映射
  lesion_types:
    0: "background"
    1: "GGO"
    2: "reticulation"
    3: "consolidation"
    4: "honeycombing"
  
  # 质量控制参数
  quality_control:
    # 最小置信度阈值
    min_confidence: 0.1
    # 最大假阳性率
    max_false_positive_rate: 0.05
    # 连通组件分析参数
    connectivity: 2
    # 形态学操作参数
    morphology:
      # 开运算核大小
      opening_kernel_size: 3
      # 闭运算核大小
      closing_kernel_size: 5

# ============================================================================
# 系统配置
# ============================================================================
system:
  # 并行处理
  parallel:
    num_workers: 4
    use_multiprocessing: true
  
  # 内存管理
  memory:
    max_memory_gb: 32
    use_memory_mapping: true
  
  # 调试配置
  debug:
    enabled: false
    max_patients: 3
    max_slices: 50
    save_debug_images: false
    debug_dir: "./debug"