# ILD分割完整流程配置文件
# 支持数据预处理、训练、推理的统一配置

# ============================================================================
# 全局配置
# ============================================================================
global:
  # 项目名称
  project_name: "ILD_Segmentation"
  # 工作目录
  work_dir: "./workspace"
  # 随机种子
  seed: 42
  # GPU设备
  device: "cuda:0"
  # 日志级别
  log_level: "INFO"

# ============================================================================
# 数据路径配置
# ============================================================================
data:
  # 原始数据路径
  raw_data:
    ct_dir: "../dataset/images"
    label_dir: "../dataset/labels"
    lung_dir: "../dataset/lungs"
    annotations_file: "../dataset/annotations/processed/processed_labels.jsonl"
    lesion_analysis_file: "../dataset/patient_lesion_analysis.json"
  
  # 病变类型映射
  lesion_type_mapping:
    0: "background"
    1: "GGO"
    2: "reticulation"
    3: "consolidation"
    4: "honeycombing"
  
  # 预处理数据路径
  preprocessed:
    output_dir: "./data/preprocessed"
    npy_dir: "./data/npy"
    npz_dir: "./data/npz"
  
  # 文件命名模式
  naming:
    ct_suffix: "_0000.nii.gz"
    label_suffix: ".nii.gz"
    lung_patterns:
      - "{case_name}_lung_mask.nii.gz"

# ============================================================================
# 数据预处理配置
# ============================================================================
preprocessing:
  # 数据划分
  data_split:
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1
    stratified: true  # 基于疾病类型分层
  

  
  # CT图像处理
  ct_processing:
    window_level: 40
    window_width: 400
    output_size: [256, 256]
    convert_to_3channel: true
    normalize_range: [0, 255]
  
  # 标签处理
  label_processing:
    # 连通组件清理
    clean_3d:
      enabled: true
      threshold: 1000  # 体素数
      connectivity: 26
    clean_2d:
      enabled: true
      threshold: 100   # 像素数
      connectivity: 8
    # 标签值验证
    validate_range: [0, 10]
  
  # 肺分割处理
  lung_processing:
    bbox_padding: 5
    fallback_to_hu: true
    hu_range: [-1000, 200]
  
  # 质量控制
  quality_control:
    min_slices_per_patient: 1
    min_lesion_area: 10
    check_file_integrity: true
  
  # 输出控制
  output:
    save_patient_splits: true
    save_slice_metadata: true
    save_statistics: true
    metadata_format: "json"

# ============================================================================
# 训练配置（预留）
# ============================================================================
training:
  # 模型配置
  model:
    name: "sam2"
    config_file: "sam2_hiera_t.yaml"
    checkpoint: "./checkpoints/sam2_hiera_tiny.pt"
  
  # 训练参数
  params:
    epochs: 500
    batch_size: 16
    learning_rate: 1e-5
    weight_decay: 1e-4
  
  # 数据加载
  dataloader:
    num_workers: 4
    pin_memory: true
    shuffle: true
  
  # 损失函数
  loss:
    dice_weight: 1.0
    ce_weight: 1.0
  
  # 保存配置
  checkpoint:
    save_dir: "./checkpoints"
    save_interval: 50
    keep_best: true

# ============================================================================
# 推理配置（预留）
# ============================================================================
inference:
  # 模型配置
  model:
    checkpoint: "./checkpoints/best_model.pth"
    config_file: "sam2_hiera_t.yaml"
  
  # 推理参数
  params:
    batch_size: 1
    output_size: [1024, 1024]
    use_3d_propagation: true
  
  # 输出配置
  output:
    save_dir: "./results"
    save_format: "nii.gz"
    save_visualization: true

# ============================================================================
# 系统配置
# ============================================================================
system:
  # 并行处理
  parallel:
    num_workers: 4
    use_multiprocessing: true
  
  # 内存管理
  memory:
    max_memory_gb: 32
    use_memory_mapping: true
  
  # 调试配置
  debug:
    enabled: false
    max_patients: 3
    max_slices: 50
    save_debug_images: false
    debug_dir: "./debug"